### ISSUE TITLE
How to dont use app secret and tennant id login or userDetails

### ISSUE THREAD

**Issue by AtaKarakas** [jdubois/spring-active-directory#2]
How to dont use app secret and tennant id, get login or userDetails

**Comment by jdubois** [comment]
You mean, in https://github.com/jdubois/spring-active-directory/blob/master/src/main/resources/application.yml ?
The tenantId is mandatory (otherwise AAD couldn't know where to connect), and same for the app secret (otherwise the app won't have the credentials to connect). So it's not possible, you need to use them.
